### ISSUE TITLE
SMTP problem 

### ISSUE THREAD

**Issue by jagadsecops** [mojtaba-komeili/MNIST-in-PyTorch#1]
Bro! I have A project,that is otp generation and verification,in that purpose i wrote a program,but in that i have a problem about smpt module,it doesn't work,it returns error,so,plz help me bro plz @mojtaba-komeili

**Comment by mojtaba-komeili** [comment]
Sorry, I am not sure what you mean by "otp generation and verification" and could you explain about your problem with "smpt module"?
